[package]
name = "webservice"
version = "0.1.0"
edition = "2024"
default-run = "teacher-service"

[dependencies]
actix-web = "4.0"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "teacher-service"